name:                advent-of-code
version:             0.1.0.0
github:              "githubuser/advent-of-code"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/advent-of-code#readme>

dependencies:
- base >= 4.7 && < 5
- attoparsec
- bytestring

default-extensions: 
- TypeApplications
- OverloadedStrings
- LambdaCase

source-dirs: solutions

executables:
  # Notice that the name of the file MUST be lowercase, otherwise It is considered a module, and must be in separated folders
  # I think, this is a haskell convention... But don't know
  day-1:
    main: day-1.hs
  day-2:
    main: day-2.hs
  day-3:
    main: day-3.hs
  day-4:
    main: day-4.hs
